### ISSUE TITLE
The execution encounters this error, and the generated file is very small

### ISSUE THREAD

**Issue by zhihaoHappyeveryday** [ip2location/ip2convert#1]
![image](https://github.com/ip2location/ip2convert/assets/49114216/69e22ccc-db16-40c3-92de-037f447291fb)
first thanks author, 
The execution encounters this error, and the generated file is very small

**Comment by zhihaoHappyeveryday** [comment]
![image](https://github.com/ip2location/ip2convert/assets/49114216/c17974f3-3b26-4c38-922f-38543ebd4aad)
normalfile

**Comment by ip2whois** [comment]
Are you using the DB5 LITE IPv6 CSV? The converter relies on the IPv6 CSV and not the IPv4 CSV.

**Comment by zhihaoHappyeveryday** [comment]
first, thanks author,  I have also used IPv6 CSV, but it gives different results for the same IP address, is there a way to convert IPv4 CSV to BIN file?
My current requirement is: I need to add 2 custom IPs to be mapped to a country, is there a best practice way to achieve this requirement?

![image](https://github.com/ip2location/ip2convert/assets/49114216/ba55e336-4e27-45a4-af2c-0eabf9f0ad5e)
![image](https://github.com/ip2location/ip2convert/assets/49114216/5666f22f-aad7-420e-942d-aef4e5aa24d7)
